.TH MQTT_INSPECTOR 1 "February 2026" "obd2-viewer 0.1.0"
.SH NAME
obd2-viewer \- OBD2 diagnostic data viewer and logger
.SH SYNOPSIS
.B obd2-viewer
.SH DESCRIPTION
.B obd2-viewer
is a GTK4 application for LOBD2 diagnostic data viewer and logger.
.SH OPTIONS
None currently supported.
.SH AUTHOR
Daniel Nylander <daniel@danielnylander.se>
.SH SEE ALSO
.BR gtk4 (7)
